---
- name: undeploy
  hosts: ec2-server
  remote_user: yunjunma
  
  tasks:  
    - name: mesage
      debug: msg="undeploy the server"

    - name: stop the Nginx
      apt: name=nginx state=absent



