---
- name: ansible
  hosts: ec2-server
  remote_user: ubuntu
  
  vars: 
   - Message: "Hello world!"

  tasks:  
    - name: mesage
      debug: msg="Hello World"

    - name: Nginx setup
      become: true
      apt: pkg=nginx state=installed update_cache=true

    - name: deploy a default html page
      become: true
      template: src=index.html.j2 dest=/var/www/html/index.html



