---
- name: undeploy
  hosts: ec2-server
  remote_user: ubuntu
  
  tasks:  
    - name: mesage
      debug: msg="undeploy the server"

    - name: stop the Nginx
      become: true
      service: name=nginx state=stopped



